name: fawran
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  http: ^1.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/cleaning_hero.jpg
    - assets/images/east_asia_flags.png
    - assets/images/african_flags.png
    - assets/images/evening_icon.png
    - assets/images/cleaning_service_card.jpg
    - assets/images/services-image.png
    - assets/images/emdad-logo.png
